aprendendodjango/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from aprendendodjango.views import HomeView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    # url(r'^$', 'include(admin.site.urls))
    # url(r'^blog/', include('blog.urls')),
    # url(r'^', include('minhaapp.urls', namespace="minhaapp")),
    url(r'^minhaapp/', include('minhaapp.urls', namespace="minhaapp")),
    url(r'^galeria/', include('galeria.urls', namespace="galeria")),
    url(r'^admin/', include(admin.site.urls)),
)

minhaapp/urls.py
from django.conf.urls import patterns, url

from minhaapp import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<pk>\d+)/vote/$', views.VoteView.as_view(), name='vote'),
)

minhaapp/models.py
from django.db import models
import datetime
from django.utils import timezone

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

aprendendodjango/views.py
#coding: utf-8

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

class HomeView(generic.TemplateView):
    template_name = 'home/base_site.html'

    def get_context_data(self, **kwargs):
        dados = super(HomeView, self).get_context_data(**kwargs)
        dados['descricao'] = 'Selecione uma das opções do menu acima.'

        return dados

minhaapp/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from minhaapp.models import Choice, Poll

class IndexView(generic.ListView):
    template_name = 'minhaapp/index.html'
    paginate_by = 2
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'minhaapp/detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'minhaapp/results.html'


class VoteView(generic.View):
    def post(self, request, *args, **kwargs):
        poll_id = kwargs['pk']
        p = get_object_or_404(Poll, pk=poll_id)
        try:
            selected_choice = p.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'minhaapp/detail.html', {
                'poll': p,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('minhaapp:results', args=(poll_id,)))

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'minhaapp/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('minhaapp:results', args=(p.id,)))

minhaapp/templates/minhaapp/detail.html
{% extends "home/base_site.html" %}

{% block conteudo %}
<h1>{{ poll.question }}</h1>
{% if error_message %}
<p>
<strong>
    {{ error_message }}
</strong>
</p>
{% endif %}
<form action="{% url 'minhaapp:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
{% endfor %}
<input type="submit" value="Vote" />
</form>
{% endblock conteudo %}

minhaapp/templates/minhaapp/index.html
{% extends "home/base_site.html" %}

{% block conteudo %}
<h3>Minhas pesquisas</h3>
    {% if latest_poll_list %}
        <ul>
        {% block pesq-menu %}
        {% for poll in latest_poll_list %}
            <li><a href="{% url 'minhaapp:detail' poll.id %}">{{ poll.question }}</a></li>
        {% endfor %}
        {% endblock pesq-menu %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock conteudo %}

minhaapp/templates/minhaapp/results.html
{% extends "home/base_site.html" %}

{% block conteudo %}
<h3>{{ poll.question }}</h3>

<ul>
    {% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'minhaapp:detail' poll.id %}">Votar novamente?</a>
{% endblock conteudo %}

templates/home/base_site.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'galeria/css/bootstrap-theme.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'galeria/css/bootstrap-theme.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'galeria/css/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'galeria/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'galeria/css/galeria.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="{% static 'galeria/js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'galeria/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'galeria/js/galeria.js' %}"></script>
    <title>Home</title>
  </head>
  <body>

    <div class="container">

      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="/">Home</a></li>
              <li><a href="{% url 'galeria:index'%}">Galeria</a></li>
              <li><a href="{% url 'minhaapp:index'%}">Pesquisas</a></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Todas pesquisas <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                {% for poll in latest_poll_list %}
                    <li><a href="{% url 'minhaapp:detail' poll.id %}">{{ poll.question }}</a></li>
                {% endfor %}
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="{% url 'admin:index'%}">Login</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </div>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        {% block conteudo %}
        {% endblock conteudo %}
        {{ descricao }}
      </div>
    </div>
  </body>
</html>